### ISSUE TITLE
URI is not hierarchical

### ISSUE THREAD

**Issue by javatlacati** [javrr-ui/SimonDice#65]
Al abrirlo en modo consola obtengo:

```
java.lang.IllegalArgumentException: URI is not hierarchical
        at java.base/java.io.File.<init>(File.java:418)
        at com.company.Sound.<init>(Sound.java:41)
        at com.company.GameWindow.initComponents(GameWindow.java:374)
        at com.company.GameWindow.<init>(GameWindow.java:145)
        at com.company.Main.modoNormal(Main.java:33)
        at com.company.Main.main(Main.java:24)
```

**Comment by javrr-ui** [comment]
@javatlacati si hiciste pull?

**Comment by javatlacati** [comment]
Se corrige con el pull.
